/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account.orders.$orderId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AccountOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/register'
    | '/account/orders'
    | '/products/$slug'
    | '/products'
    | '/account/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/register'
    | '/account/orders'
    | '/products/$slug'
    | '/products'
    | '/account/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/register'
    | '/account/orders'
    | '/products/$slug'
    | '/products/'
    | '/account/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
  }
}

interface AccountOrdersRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
