// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type User struct {
	ID                  uuid.UUID   `json:"id"`
	Email               string      `json:"email"`
	EmailVerified       bool        `json:"email_verified"`
	PasswordHash        string      `json:"password_hash"`
	Phone               *string     `json:"phone"`
	PhoneVerified       bool        `json:"phone_verified"`
	AvatarUrl           *string     `json:"avatar_url"`
	Status              string      `json:"status"`
	Role                string      `json:"role"`
	FailedLoginAttempts int32       `json:"failed_login_attempts"`
	LockedUntil         *time.Time  `json:"locked_until"`
	LastLoginAt         *time.Time  `json:"last_login_at"`
	LastLoginIp         pqtype.Inet `json:"last_login_ip"`
	PasswordChangedAt   *time.Time  `json:"password_changed_at"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	DeletedAt           *time.Time  `json:"deleted_at"`
}
