// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package models

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    created_at,
    updated_at
) VALUES (
    $1, $2, NOW(), NOW()
) RETURNING id, email, email_verified, password_hash, phone, phone_verified, avatar_url, status, role, failed_login_attempts, locked_until, last_login_at, last_login_ip, password_changed_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Phone,
		&i.PhoneVerified,
		&i.AvatarUrl,
		&i.Status,
		&i.Role,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified, password_hash, phone, phone_verified, avatar_url, status, role, failed_login_attempts, locked_until, last_login_at, last_login_ip, password_changed_at, created_at, updated_at, deleted_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Phone,
		&i.PhoneVerified,
		&i.AvatarUrl,
		&i.Status,
		&i.Role,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    id,
    email,
    email_verified,
    phone,
    phone_verified,
    avatar_url,
    status,
    role,
    last_login_at,
    created_at,
    updated_at
FROM users
WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID            uuid.UUID  `json:"id"`
	Email         string     `json:"email"`
	EmailVerified bool       `json:"email_verified"`
	Phone         *string    `json:"phone"`
	PhoneVerified bool       `json:"phone_verified"`
	AvatarUrl     *string    `json:"avatar_url"`
	Status        string     `json:"status"`
	Role          string     `json:"role"`
	LastLoginAt   *time.Time `json:"last_login_at"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.AvatarUrl,
		&i.Status,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT 
    id,
    email,
    email_verified,
    phone,
    phone_verified,
    avatar_url,
    status,
    role,
    last_login_at,
    created_at,
    updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID            uuid.UUID  `json:"id"`
	Email         string     `json:"email"`
	EmailVerified bool       `json:"email_verified"`
	Phone         *string    `json:"phone"`
	PhoneVerified bool       `json:"phone_verified"`
	AvatarUrl     *string    `json:"avatar_url"`
	Status        string     `json:"status"`
	Role          string     `json:"role"`
	LastLoginAt   *time.Time `json:"last_login_at"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.PhoneVerified,
			&i.AvatarUrl,
			&i.Status,
			&i.Role,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    email = COALESCE($2, email),
    email_verified = COALESCE($3, email_verified),
    phone = COALESCE($4, phone),
    phone_verified = COALESCE($5, phone_verified),
    avatar_url = COALESCE($6, avatar_url),
    status = COALESCE($7, status),
    role = COALESCE($8, role),
    failed_login_attempts = COALESCE($9, failed_login_attempts),
    locked_until = COALESCE($10, locked_until),
    last_login_at = COALESCE($11, last_login_at),
    last_login_ip = COALESCE($12, last_login_ip),
    password_changed_at = COALESCE($13, password_changed_at),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, email_verified, password_hash, phone, phone_verified, avatar_url, status, role, failed_login_attempts, locked_until, last_login_at, last_login_ip, password_changed_at, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID                  uuid.UUID     `json:"id"`
	Email               *string       `json:"email"`
	EmailVerified       sql.NullBool  `json:"email_verified"`
	Phone               *string       `json:"phone"`
	PhoneVerified       sql.NullBool  `json:"phone_verified"`
	AvatarUrl           *string       `json:"avatar_url"`
	Status              *string       `json:"status"`
	Role                *string       `json:"role"`
	FailedLoginAttempts sql.NullInt32 `json:"failed_login_attempts"`
	LockedUntil         *time.Time    `json:"locked_until"`
	LastLoginAt         *time.Time    `json:"last_login_at"`
	LastLoginIp         pqtype.Inet   `json:"last_login_ip"`
	PasswordChangedAt   *time.Time    `json:"password_changed_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.EmailVerified,
		arg.Phone,
		arg.PhoneVerified,
		arg.AvatarUrl,
		arg.Status,
		arg.Role,
		arg.FailedLoginAttempts,
		arg.LockedUntil,
		arg.LastLoginAt,
		arg.LastLoginIp,
		arg.PasswordChangedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Phone,
		&i.PhoneVerified,
		&i.AvatarUrl,
		&i.Status,
		&i.Role,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET
    password_hash = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
